### ISSUE TITLE
Git clone problem

### ISSUE THREAD

**Issue by VPRzhou** [germain-hug/S2DHM#1]
Hi,Great word you did! But I have a problem when I run the command  "git clone https://github.com/germain-hug/S2D_Hypercolumn_Matching.git".Could you tell me how to do the username and password question.Looking forward your reply,thank you.

**Comment by germain-hug** [comment]
Hi!
Sorry about the late response, the actual link should be https://github.com/germain-hug/S2DHM.git (the same as the git repo). I just updated the README apologies for the confusion.
