### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by VPRzhou** [germain-hug/S2DHM#2]
Sorry,I have another question.I have read your paper"Improving Nighttime Retrieval-Based Localization"recently.Something I want to learn clearly,But the source code can not be available as you said in the papar"https://github.com/germain-hug/Improving-Nighttime-Localization".IIf you have completed your code,I will apprecate it.

**Comment by germain-hug** [comment]
Hi and sorry about the late response,
Apologies I haven't had the time to release the source code yet although I believe it should not be too hard to implement. Note that S2DHM also yields much better results.
