### ISSUE TITLE
Running S2DHM on new dataset

### ISSUE THREAD

**Issue by tsattler** [germain-hug/S2DHM#5]
Hi @germain-hug 

thanks for releasing the code.
I wonder if you have any experience in running your method on new datasets outside those used for the long-term visual localization challenge?

Thanks!

Best,
Torsten

**Comment by germain-hug** [comment]
Hi Torsten,
I have not experienced running the method on other datasets such as InLoc, but I'm planning on doing so in the future!
Cheers,
Hugo

**Comment by tsattler** [comment]
Hi Hugo,

thanks!
Since Ara contacted you separately, I'll close this issue.

Best,
Torsten
