### ISSUE TITLE
Intrinsics used for RANSAC PnP

### ISSUE THREAD

**Issue by lxxue** [germain-hug/S2DHM#6]
Hi, 

Thanks for the well-written and organized code. I have a question here:

https://github.com/germain-hug/S2DHM/blob/0b9df9c60393528c58957db0cc13ec7813bd2ecc/s2dhm/pose_prediction/sparse_to_dense_predictor.py#L90-L104

Here we are using the matched 2D points in the query image and corresponding 3D points to estimate the camera pose. Since it is about the query image, I feel like we should use the intrinsics and distortion coefficients of the query image, instead of the local reconstruction ones (probably belongs to the reference image)?

**Comment by germain-hug** [comment]
Hi and apologies for the late reply,
Indeed you are correct the query camera parameters should be used, this is an error I had corrected locally but forgot to update on this repository.

**Comment by lxxue** [comment]
Hi Hugo,

we tried fixing this bug but we found that with this bug, the performance is significantly better than the fixed version on the robotcar's night split:

with reference intrinsics: 

28.4 / 69.5 / 94.6

with query intrinsics: 

21.5 / 61.3 / 94.5 （similar to the figures in the paper)

Do you have any idea about the reason behind this?

**Comment by germain-hug** [comment]
Hi,

This is indeed quite strange and unexpected, were you able to compare the
query intrinsics with the ones from the database to check if
they're correct?

**Comment by lxxue** [comment]
Hi,

They are different but I don't know which one is correct. I also evaluate these two on the cmu dataset:

with reference intrinsics:

          urban                 suburban                 park
47.2 / 71.5 / 93.3 | 39.3 / 63.8 / 91.5 | 26.0 / 47.5 / 80.2 (far below the figures in the paper)


with query intrinsics:

          urban                 suburban                 park
3.3 / 11.9 / 87.0 | 2.0 / 9.6 / 87.6 | 1.8 / 8.5 / 73.9

I wonder if you can reproduce the results in the paper with the default setting or there are some crucial changes not in repo? Also, this result suggests using reference image's intrinsics/distortion coefficients, which is quite strange.
